## SQL Read

In [1]:
import sqlite3 as sq3
import pandas.io.sql as pds
import pandas as pd

In [3]:
# mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
file_path = '/content/drive/MyDrive/datasets/music_playlist.db'

In [4]:
con = sq3.Connection(file_path)
con

### Reading data

In [5]:
# write query
query = 'SELECT * FROM music_playlist;'

# Execute query
data = pds.read_sql(query, con)
data.head()

,Song_Title,Artist,Genre,Release_Year,Duration_Minutes,Listened_Date,Platform
0,Faded,Alan Walker,Electronic,2024,4.02,2024-02-10,Apple Music
1,Blinding Lights,The Weeknd,Synth-pop,2018,4.45,2024-05-30,Zing MP3
2,Faded,Alan Walker,Electronic,2024,4.86,2024-05-07,Zing MP3
3,Faded,Alan Walker,Electronic,2012,4.92,2024-03-19,YouTube
4,Bohemian Rhapsody,Queen,Rock,2023,3.9,2024-01-16,Apple Music

In [7]:
# write query
query = 'SELECT Song_Title FROM music_playlist;'

# Execute query
data = pds.read_sql(query, con)
data.head()

          Song_Title
0              Faded
1    Blinding Lights
2              Faded
3              Faded
4  Bohemian Rhapsody

In [10]:
# write query
query = 'SELECT COUNT(*) FROM music_playlist;'

# Execute query
data = pds.read_sql(query, con)
data

   COUNT(*)
0       100

In [11]:
# write query
query = 'SELECT DISTINCT Genre FROM music_playlist;'

# Execute query
data = pds.read_sql(query, con)
data

          Genre
0    Electronic
1     Synth-pop
2          Rock
3    Pop Ballad
4         Indie
5     Latin Pop
6           Pop
7      Pop Rock
8          Soul
9       Hip Hop
10  Alternative
11   Electropop
12          R&B

In [19]:
query = '''
SELECT Artist, COUNT(*) AS num_songs 
    FROM music_playlist
    GROUP BY Artist
    ORDER BY num_songs desc;
'''
# Execute query
data = pds.read_sql(query, con)
data

                           Artist  num_songs
0                      Ed Sheeran         15
1                      The Weeknd          9
2                     Alan Walker          9
3   The Kid LAROI & Justin Bieber          7
4                       Passenger          7
5   Shawn Mendes & Camila Cabello          6
6                     Tones and I          5
7                   Billie Eilish          5
8                           Adele          5
9    Wiz Khalifa ft. Charlie Puth          4
10         Post Malone & Swae Lee          4
11                    OneRepublic          4
12                  Justin Bieber          4
13                       Dua Lipa          4
14                 Camila Cabello          4
15                          Queen          3
16         Billie Eilish & Khalid          3
17                Imagine Dragons          2

------------------------------------------

| <img src="https://github.com/madhawapolkotuwa.png" width="80" style="border-radius: 50%;"> | **MPCoding**<br>*Machine Learning Tutorial Series*<br><br> [![YouTube](https://img.shields.io/badge/YouTube-%23FF0000.svg?style=for-the-badge&logo=YouTube&logoColor=white)](https://www.youtube.com/@MP-Coding) [![GitHub](https://img.shields.io/badge/github-repo-blue?logo=github)](https://github.com/madhawapolkotuwa) |
|---|---|

<p align="left" style="font-size: 0.85em; color: gray; margin-top: 10px;">
  © 2026 MPCoding. Educational materials are free to use with proper attribution.
</p>